export const USER_REPOSITORY = 'USER_REPOSITORY';
export const NEWS_REPOSITORY = 'NEWS_REPOSITORY';
export const COMMENTS_REPOSITORY = 'COMMENTS_REPOSITORY';
export const FILE_SERVICE = 'FILE_SERVICE';
export const SEQUELIZE = 'SEQUELIZE';
